name: CI - Gradle Build

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing

jobs:
  build:
    name: Build y Pruebas (Gradle)
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permisos a Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar la aplicación
        run: ./gradlew build -x test

      - name: Ejecutar pruebas
        run: ./gradlew test


      - name: Compilar la aplicación
        run: mvn clean install -DskipTests

      - name: Ejecutar pruebas
        run: mvn test
