name: CD - Gradle Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Despliegue Continuo Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permisos al wrapper de Gradle
        run: chmod +x ./gradlew

      - name: Compilar aplicación
        run: ./gradlew build -x test

      - name: Ejecutar pruebas
        run: ./gradlew test

      - name: Generar JAR ejecutable
        run: ./gradlew bootJar

      - name: Simular publicación de artefacto
        run: |
          echo "El archivo generado es:"
          ls -lh build/libs/*.jar
          echo "Publicación simulada completada"
